### ISSUE TITLE
Expose IFormatProvider

### ISSUE THREAD

**Issue by stanisls** [ThiagoBarradas/serilog-sinks-newrelic-logs#1]
Hi.

This is a reference to the issue, raised on my serilog-sinks-newreliclogs repo: https://github.com/stanisls/serilog-sinks-newreliclogs/issues/3

I think the best course of action is to deprecate my repo and nuget package, seeing at you added .NET Core 3.1 support (something that I was about to start on now) and did a few refactoring improvements to the code base, so there is no need to reinvent the wheel.

I created a branch off `develop` to fix the IFormatProvider issue. If you could add me as a contributor, I will push it to the repo for review. It would present a lower overhead than going through yet-another-fork PR.

**Comment by ThiagoBarradas** [comment]
Thx for contact me!!

I will add you as contributor in this project. This project works with Git Flow.. When you open a bugfix/hotfix/feature and push your code, a preview release is released by CI flow. After finish (by Gitflow, that generates tag) a final release is created.

Always use the next semantic number..  Example, for some feature or bugfix increase the minor number.. Current 1.0.1, you need to create 1.1.0 (git flow feature start 1.1.0) and hotfix 1.0.2, increasing patch number (git flow hotfix start 1.0.2).

Any questions you can talk with me here:

Whatsapp: +55 21 993299143
https://www.linkedin.com/in/thiagobarradas/

Thx again ;)

**Comment by kiriasCMNH** [comment]
Hello @ThiagoBarradas , 
I was wondering if this feature was added at some point or if it is still a work in progress, haven't seen any additional updates on the repo nor in nuget.
