### ISSUE TITLE
Support appsettings.json configuration

### ISSUE THREAD

**Issue by andreflourenco** [ThiagoBarradas/serilog-sinks-newrelic-logs#2]
### Status

TASK

### Checklist

- [_] Support appsettings.json configuration

### Expected behaviour

I believe it should look something like the following:

```
...
"Serilog": {
	"WriteTo": [
		{
			"Name": "NewRelic",
			"Args": {
				"endpointUrl": "https://log-api.newrelic.com/log/v1",
				"applicationName": "Serilog.Sinks.NewRelic.Sample",
				"licenseKey": "[Your API key]"
			}
		}
	]
}
...
```

### Actual behaviour

Did not see any example of appsettings.json based configuration in the docs.

### Environment

NET Core 3.1

### Logs / Stack trace

n/a

**Comment by andreflourenco** [comment]
I've tested the sample project included in the source and it seems to work fine with the [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration) package so no code changes are necessary. 

However it would be nice to add the following information to the documentation:

### JSON configuration

It is possible to configure the sink using [Serilog.Settings.Configuration](https://github.com/serilog/serilog-settings-configuration) by specifying the license key and other desired parameters in `appsettings.json`:

```
{
  "Serilog": {
    "Using": [ "Serilog.Sinks.NewRelic.Logs" ],
    "WriteTo": [
      {
        "Name": "NewRelicLogs",
        "Args": {
          "applicationName": "NewRelicLogTestSample",
          "licenseKey": "58e9892abd3f09d91b0db0d0e9e95628FFFFNRAL"
          //... other parameters
        }
      }
    ],
    "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId", "WithNewRelicLogsInContext" ]
  }
}
```

**Comment by ThiagoBarradas** [comment]
Hello! Thx for your question! It's possible but isn't in readme / documentation. I will add the following instructions in readme. Thx again ;)
