### ISSUE TITLE
Include Exception information

### ISSUE THREAD

**Issue by andreflourenco** [ThiagoBarradas/serilog-sinks-newrelic-logs#4]
### Status

TASK

### Checklist

Include 

- [_] Include exception information in the logs sent to New Relic

### Expected behaviour

The exception information (`ToString()`) should be sent as a property in the New Relic payload. 

```
{
  "application": "NewRelicLogTestSample",
  "exception": "System.ApplicationException: This is an exception raised to test the New Relic API\r\n   at Serilog.Sinks.NewRelic.Logs.Playground.NETCore31.Program.Main() ...",
  "level": "Error",
  "MachineName": "\"PC\"",
  "message": "Error whilst testing the Serilog.Sinks.NewRelic.Logs.Sample",
  "stack_trace": "   at Serilog.Sinks.NewRelic.Logs.Playground.NETCore31.Program.Main() ...",
  "ThreadId": 1,
  "timestamp": 1612292159292
}
```

### Actual behaviour

Currently only the stack trace of the exception is sent.

```
{
  "application": "NewRelicLogTestSample",
  "level": "Error",
  "MachineName": "\"PC\"",
  "message": "Error whilst testing the Serilog.Sinks.NewRelic.Logs.Sample",
  "stack_trace": "   at Serilog.Sinks.NewRelic.Logs.Playground.NETCore31.Program.Main() ...",
  "ThreadId": 1,
  "timestamp": 1612291939076
}
```

This was obtained from the New Relic console after running the sample project. The message in the ApplicationException `This is an exception raised to test the New Relic API` is completely lost.

### Environment

n/a

### Logs / Stack trace

n/a

**Comment by georgechond94** [comment]
@andreflourenco +1 There is a PR opened for it: https://github.com/ThiagoBarradas/serilog-sinks-newrelic-logs/pull/3

**Comment by ThiagoBarradas** [comment]
Hello, the PR was merged and new version released! Thx guys!

https://www.nuget.org/packages/Serilog.Sinks.NewRelic.Logs/1.1.0
